services:
    nginx:
        container_name: minilink-nginx
        image: nginx:1.27-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/ssl:/etc/nginx/ssl
            - ./:/var/www
        depends_on:
            - php

    php:
        build: .docker/php
        working_dir: /var/www
        container_name: minilink-php
        volumes:
            - .:/var/www